version: '3.9'
services:
  backend:
    build: ./back-end-rx
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb+srv://starmerals:rxagro@cluster1.hce89cy.mongodb.net/

  frontend:
    build: ./front-end-rx
    ports:
      - '3000:3000'


